### ISSUE TITLE
Actions on main branch failing

### ISSUE THREAD

**Issue by raph-luc** [ansys/pysystem-coupling#159]
Actions on main branch failing for the past two weeks or so, on the "upload dev documentation" step, with the error: 

`The 'ansys' organization has enabled or enforced SAML SSO. To access
  this repository, visit https://github.com/orgs/ansys/sso?authorization_request=AWECY2TFQV5NGLYWO37ZODTEO5L77A5PN5ZGOYLONF5GC5DJN5XF62LEZYB663VUVVRXEZLEMVXHI2LBNRPWSZGOF2OOWYFPMNZGKZDFNZ2GSYLML52HS4DFVNHWC5LUNBAWGY3FONZQ
  and try your request again.
  fatal: unable to access 'https://github.com/ansys/pysystem-coupling.git/': The requested URL returned error: 403
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"`

Think a token or password update is needed?

See
https://github.com/ansys/pysystem-coupling/actions/runs/5004751008/jobs/8968048179
https://github.com/ansys/pysystem-coupling/actions/runs/5133291896/jobs/9235920879

**Comment by iboyd-ansys** [comment]
Thanks for this and apologies for not spotting it until now. I have largely been away from pyansys for a couple of months.

You were correct that a different key was needed - for some reason the wrong one had been used, but it had been working before May.

Fixed in [PR 167](https://github.com/ansys/pysystem-coupling/pull/167).
